# Generated by Django 5.1.3 on 2024-11-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
