# Generated by Django 5.1.3 on 2024-11-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_doctor_username"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="animal",
            table="animals",
        ),
        migrations.AlterModelTable(
            name="consultation",
            table="consultations",
        ),
        migrations.AlterModelTable(
            name="diagnosis",
            table="diagnoses",
        ),
        migrations.AlterModelTable(
            name="disease",
            table="diseases",
        ),
        migrations.AlterModelTable(
            name="doctor",
            table="doctors",
        ),
        migrations.AlterModelTable(
            name="owner",
            table="owners",
        ),
        migrations.AlterModelTable(
            name="treatment",
            table="treatments",
        ),
    ]
