# Generated by Django 5.1.3 on 2024-11-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_animal_table_alter_consultation_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="email",
            field=models.CharField(max_length=100),
        ),
    ]
