# Generated by Django 5.1.3 on 2024-11-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_owner_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={"managed": True},
        ),
    ]
