# Generated by Django 5.1.3 on 2024-11-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_doctor_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animal",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="consultation",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="diagnosis",
            options={"managed": True, "verbose_name_plural": "Diagnoses"},
        ),
        migrations.AlterModelOptions(
            name="disease",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="owner",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="treatment",
            options={"managed": True},
        ),
    ]
