# Generated by Django 5.1.3 on 2024-12-01 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_consultation_doctor_alter_doctor_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="consultation",
            name="consultation_date",
            field=models.DateTimeField(),
        ),
    ]
